apiVersion: v1
kind: Secret
metadata:
  name: {{ include "goph-profile.fullname" . }}-secret
  labels:
    {{- include "goph-profile.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URI: {{ .Values.secretEnv.databaseURI | quote }}
  MINIO_ACCESS_KEY: {{ .Values.secretEnv.minioAccessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.secretEnv.minioSecretKey | quote }}
