{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "goph-profile.componentName" (dict "ctx" . "name" "profiled") }}
  labels:
    {{- include "goph-profile.componentLabels" (dict "ctx" . "name" "profiled") | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "goph-profile.componentSelectorLabels" (dict "ctx" . "name" "profiled") | nindent 6 }}
  endpoints:
    - port: metrics
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
