// Code generated by MockGen. DO NOT EDIT.
// Source: group_handler.go
//
// Generated by this command:
//
//	mockgen -source=group_handler.go -destination=mocks/group_handler_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGroupHandler is a mock of GroupHandler interface.
type MockGroupHandler struct {
	ctrl     *gomock.Controller
	recorder *MockGroupHandlerMockRecorder
	isgomock struct{}
}

// MockGroupHandlerMockRecorder is the mock recorder for MockGroupHandler.
type MockGroupHandlerMockRecorder struct {
	mock *MockGroupHandler
}

// NewMockGroupHandler creates a new mock instance.
func NewMockGroupHandler(ctrl *gomock.Controller) *MockGroupHandler {
	mock := &MockGroupHandler{ctrl: ctrl}
	mock.recorder = &MockGroupHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupHandler) EXPECT() *MockGroupHandlerMockRecorder {
	return m.recorder
}

// OnDelete mocks base method.
func (m *MockGroupHandler) OnDelete(ctx context.Context, payload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnDelete", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnDelete indicates an expected call of OnDelete.
func (mr *MockGroupHandlerMockRecorder) OnDelete(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnDelete", reflect.TypeOf((*MockGroupHandler)(nil).OnDelete), ctx, payload)
}

// OnUpload mocks base method.
func (m *MockGroupHandler) OnUpload(ctx context.Context, payload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnUpload", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnUpload indicates an expected call of OnUpload.
func (mr *MockGroupHandlerMockRecorder) OnUpload(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnUpload", reflect.TypeOf((*MockGroupHandler)(nil).OnUpload), ctx, payload)
}
