// Code generated by MockGen. DO NOT EDIT.
// Source: publisher.go
//
// Generated by this command:
//
//	mockgen -source=publisher.go -destination=mocks/publisher_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ports "github.com/arvaliullin/goph-profile/internal/core/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEventPublisher) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEventPublisherMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEventPublisher)(nil).Close))
}

// PublishDelete mocks base method.
func (m *MockEventPublisher) PublishDelete(ctx context.Context, e ports.AvatarDeleteEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishDelete", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishDelete indicates an expected call of PublishDelete.
func (mr *MockEventPublisherMockRecorder) PublishDelete(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishDelete", reflect.TypeOf((*MockEventPublisher)(nil).PublishDelete), ctx, e)
}

// PublishUpload mocks base method.
func (m *MockEventPublisher) PublishUpload(ctx context.Context, e ports.AvatarUploadEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishUpload", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishUpload indicates an expected call of PublishUpload.
func (mr *MockEventPublisherMockRecorder) PublishUpload(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishUpload", reflect.TypeOf((*MockEventPublisher)(nil).PublishUpload), ctx, e)
}
