// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/arvaliullin/goph-profile/internal/core/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAvatarRepository is a mock of AvatarRepository interface.
type MockAvatarRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarRepositoryMockRecorder
	isgomock struct{}
}

// MockAvatarRepositoryMockRecorder is the mock recorder for MockAvatarRepository.
type MockAvatarRepositoryMockRecorder struct {
	mock *MockAvatarRepository
}

// NewMockAvatarRepository creates a new mock instance.
func NewMockAvatarRepository(ctrl *gomock.Controller) *MockAvatarRepository {
	mock := &MockAvatarRepository{ctrl: ctrl}
	mock.recorder = &MockAvatarRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarRepository) EXPECT() *MockAvatarRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAvatarRepository) Create(ctx context.Context, a *domain.Avatar) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAvatarRepositoryMockRecorder) Create(ctx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAvatarRepository)(nil).Create), ctx, a)
}

// GetByID mocks base method.
func (m *MockAvatarRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAvatarRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAvatarRepository)(nil).GetByID), ctx, id)
}

// GetLatestByUserID mocks base method.
func (m *MockAvatarRepository) GetLatestByUserID(ctx context.Context, userID string) (*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestByUserID indicates an expected call of GetLatestByUserID.
func (mr *MockAvatarRepositoryMockRecorder) GetLatestByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestByUserID", reflect.TypeOf((*MockAvatarRepository)(nil).GetLatestByUserID), ctx, userID)
}

// ListByUserID mocks base method.
func (m *MockAvatarRepository) ListByUserID(ctx context.Context, userID string) ([]domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID)
	ret0, _ := ret[0].([]domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockAvatarRepositoryMockRecorder) ListByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockAvatarRepository)(nil).ListByUserID), ctx, userID)
}

// SoftDelete mocks base method.
func (m *MockAvatarRepository) SoftDelete(ctx context.Context, id uuid.UUID, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockAvatarRepositoryMockRecorder) SoftDelete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockAvatarRepository)(nil).SoftDelete), ctx, id, userID)
}

// SoftDeleteLatestByUserID mocks base method.
func (m *MockAvatarRepository) SoftDeleteLatestByUserID(ctx context.Context, userID, requestUserID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteLatestByUserID", ctx, userID, requestUserID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDeleteLatestByUserID indicates an expected call of SoftDeleteLatestByUserID.
func (mr *MockAvatarRepositoryMockRecorder) SoftDeleteLatestByUserID(ctx, userID, requestUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteLatestByUserID", reflect.TypeOf((*MockAvatarRepository)(nil).SoftDeleteLatestByUserID), ctx, userID, requestUserID)
}

// UpdateOriginalDimensions mocks base method.
func (m *MockAvatarRepository) UpdateOriginalDimensions(ctx context.Context, id uuid.UUID, w, h int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOriginalDimensions", ctx, id, w, h)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOriginalDimensions indicates an expected call of UpdateOriginalDimensions.
func (mr *MockAvatarRepositoryMockRecorder) UpdateOriginalDimensions(ctx, id, w, h any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOriginalDimensions", reflect.TypeOf((*MockAvatarRepository)(nil).UpdateOriginalDimensions), ctx, id, w, h)
}

// UpdateProcessingStatus mocks base method.
func (m *MockAvatarRepository) UpdateProcessingStatus(ctx context.Context, id uuid.UUID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProcessingStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProcessingStatus indicates an expected call of UpdateProcessingStatus.
func (mr *MockAvatarRepositoryMockRecorder) UpdateProcessingStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProcessingStatus", reflect.TypeOf((*MockAvatarRepository)(nil).UpdateProcessingStatus), ctx, id, status)
}

// UpdateThumbnailKeys mocks base method.
func (m *MockAvatarRepository) UpdateThumbnailKeys(ctx context.Context, id uuid.UUID, keys map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateThumbnailKeys", ctx, id, keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateThumbnailKeys indicates an expected call of UpdateThumbnailKeys.
func (mr *MockAvatarRepositoryMockRecorder) UpdateThumbnailKeys(ctx, id, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateThumbnailKeys", reflect.TypeOf((*MockAvatarRepository)(nil).UpdateThumbnailKeys), ctx, id, keys)
}
