// Code generated by MockGen. DO NOT EDIT.
// Source: service_contract.go
//
// Generated by this command:
//
//	mockgen -source=service_contract.go -destination=mocks/service_contract_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	domain "github.com/arvaliullin/goph-profile/internal/core/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAvatarService is a mock of AvatarService interface.
type MockAvatarService struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarServiceMockRecorder
	isgomock struct{}
}

// MockAvatarServiceMockRecorder is the mock recorder for MockAvatarService.
type MockAvatarServiceMockRecorder struct {
	mock *MockAvatarService
}

// NewMockAvatarService creates a new mock instance.
func NewMockAvatarService(ctrl *gomock.Controller) *MockAvatarService {
	mock := &MockAvatarService{ctrl: ctrl}
	mock.recorder = &MockAvatarServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarService) EXPECT() *MockAvatarServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockAvatarService) Delete(ctx context.Context, id uuid.UUID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAvatarServiceMockRecorder) Delete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAvatarService)(nil).Delete), ctx, id, userID)
}

// DeleteForUser mocks base method.
func (m *MockAvatarService) DeleteForUser(ctx context.Context, userID, requestUserID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteForUser", ctx, userID, requestUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteForUser indicates an expected call of DeleteForUser.
func (mr *MockAvatarServiceMockRecorder) DeleteForUser(ctx, userID, requestUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteForUser", reflect.TypeOf((*MockAvatarService)(nil).DeleteForUser), ctx, userID, requestUserID)
}

// GetImage mocks base method.
func (m *MockAvatarService) GetImage(ctx context.Context, id uuid.UUID, size, format string) (io.ReadCloser, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", ctx, id, size, format)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetImage indicates an expected call of GetImage.
func (mr *MockAvatarServiceMockRecorder) GetImage(ctx, id, size, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockAvatarService)(nil).GetImage), ctx, id, size, format)
}

// GetImageForUser mocks base method.
func (m *MockAvatarService) GetImageForUser(ctx context.Context, userID string) (io.ReadCloser, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImageForUser", ctx, userID)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetImageForUser indicates an expected call of GetImageForUser.
func (mr *MockAvatarServiceMockRecorder) GetImageForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImageForUser", reflect.TypeOf((*MockAvatarService)(nil).GetImageForUser), ctx, userID)
}

// ListMetadata mocks base method.
func (m *MockAvatarService) ListMetadata(ctx context.Context, userID string) ([]domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMetadata", ctx, userID)
	ret0, _ := ret[0].([]domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMetadata indicates an expected call of ListMetadata.
func (mr *MockAvatarServiceMockRecorder) ListMetadata(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMetadata", reflect.TypeOf((*MockAvatarService)(nil).ListMetadata), ctx, userID)
}

// Metadata mocks base method.
func (m *MockAvatarService) Metadata(ctx context.Context, id uuid.UUID) (*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Metadata", ctx, id)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Metadata indicates an expected call of Metadata.
func (mr *MockAvatarServiceMockRecorder) Metadata(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metadata", reflect.TypeOf((*MockAvatarService)(nil).Metadata), ctx, id)
}

// Upload mocks base method.
func (m *MockAvatarService) Upload(ctx context.Context, userID, fileName, contentType string, r io.Reader, size int64) (*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, userID, fileName, contentType, r, size)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockAvatarServiceMockRecorder) Upload(ctx, userID, fileName, contentType, r, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockAvatarService)(nil).Upload), ctx, userID, fileName, contentType, r, size)
}
